config/routes.rb
Rails.application.routes.draw do
  resources :comments

  root 'static_pages#home'

  get 'room/index'

  get 'room/create'

  get 'room/party'

  get 'static_pages/home'
  match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
  devise_for :users
  resources :tests

  resources :courses do
    resources :lessons
  end

  resources :rooms
  resources :users, only: [:show]
 
  resources :lessons do
    resources :tests
  end

  resources :lessons do
    resources :documents
    resources :test_results
  end

  resources :tests do
    resources :questions
  end

  resources :courses do
    resources :comments
  end

  post 'tests/solve' => 'tests#solve', as: :test_solve

end

app/models/test_result.rb
class TestResult < ActiveRecord::Base
  include PublicActivity::Model
  belongs_to :user
  belongs_to :test
  has_many :user_anserws
  has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy

  validates_presence_of :user
  validates_presence_of :test
  validates_uniqueness_of :test , scope: :user , message: "has already been taken! Changes won't be saved!"

  validates_presence_of :max
  validates_presence_of :points

  attr_accessor :questions_results_set

  def self.createAndSafe(test, userResult, currentUser)
    testResult = TestResult.new({user: currentUser, test: test, max: test.questions.count, points: 0})
    testResult.questions_results_set = []
    test.questions.all.each do |question|
      testResult.questions_results_set << question
      processAnswer(question, testResult, userResult)
    end
    testResult.save
    testResult
  end

  def self.processAnswer(question, testResult, userResult)
    error = false
    question.user_answers = []
    question.anserws.each do |answer|
      isCorrect = userResult!=nil && checkIfCorrect(answer, userResult[question.id.to_s])
      question.user_answers << testResult.user_anserws.build({anserw: answer, correct: isCorrect})
      error = true unless isCorrect
    end
    testResult.points+=1 unless error
  end

  def self.checkIfCorrect(answer, userQuestion)
    userAnswer = userQuestion != nil ? userQuestion.find_index(answer.id.to_s) : nil
    return (userAnswer == nil) ? !answer.correct : answer.correct
  end
end

app/controllers/test_results_controller.rb
class TestResultsController < ApplicationController
  before_filter :find_lesson , only: [:index]
  before_filter :find_test_result , only: [:show]

  decorates_assigned :lesson

  def index
    @results = @lesson.findTestResults
  end

  def show
  end

  private
    def find_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    def find_test_result
      find_lesson
      @result = TestResult.find(params[:id])
    end
end

app/views/test_results/index.html.haml
.row
	.col-md-8
		.panel.panel-default
			.panel-heading= "Solved tests in lesson: \"#{@lesson.title}\""

			-if @results.any?
				%table.table
					%thead
						%tr
							%th User
							%th Points
							%th
					%tbody
						-@results.each do |result|
							%tr
								%td= result.user.email
								%td= "#{result.points}/#{result.max}"
								%td= link_to "Link", [result.test.lesson, result]
			-else
				"No tests solved for this lesson"
	.col-md-4
		.panel.panel-default
			.panel-heading Sidebar
			.panel-body
				%div= link_to "Go back to lesson", [@lesson.course, @lesson]

app/views/test_results/show.html.haml
.row
	.col-md-8
		.panel.panel-default
			.panel-heading
				= "#{@result.user.email} - Lesson: \"#{@lesson.title}\""
				%span.pull-right.label.label-info= "#{@result.points}/#{@result.max} points"
			.list-group
				-@result.test.questions.each do |question|
					.list-group-item
						%strong= "#{question.content}:"
						-question.getTestResultAnswers(@result).each do |answer|
							%br
							=check_box_tag nil, nil, isChecked(answer), disabled: true
							%span{class: resultShowClass(answer)}= answer.anserw.content

	.col-md-4
		.panel.panel-default
			.panel-heading Sidebar
			.panel-body
				%div= link_to "Go back to results list", lesson_test_results_path
				%div= link_to "Go back to test", [@lesson, @result.test]
				%div= link_to "Go back to lesson", [@lesson.course, @lesson]