config/routes.rb
Rails.application.routes.draw do
  resources :comments

  root 'static_pages#home'

  get 'room/index'

  get 'room/create'

  get 'room/party'

  get 'static_pages/home'
  match '/party/:id', :to => "rooms#party", :as => :party, :via => :get
  devise_for :users
  resources :tests

  resources :courses do
    resources :lessons
  end

  resources :rooms
  resources :users, only: [:show]
 
  resources :lessons do
    resources :tests
  end

  resources :lessons do
    resources :documents
    resources :test_results
  end

  resources :tests do
    resources :questions
  end

  resources :courses do
    resources :comments
  end

  post 'tests/solve' => 'tests#solve', as: :test_solve

end

app/models/room.rb
class Room < ActiveRecord::Base
  include PublicActivity::Model

  has_and_belongs_to_many :users, :join_table => "rooms_users", :class_name => "User"
  validates :name, uniqueness: true
end

app/controllers/rooms_controller.rb
require "opentok"
class RoomsController < ApplicationController
  before_filter :current_room, :only => [:destroy,:party]
  def index
    @rooms = Room.where(public: true).order("created_at DESC")
    @new_room = Room.new
  end



  def new
  end

  def create
    params.permit!
    @new_room = Room.new(params[:room])
    opentok_token = OpenTokService.new(@new_room).generate_token
    respond_to do |format|
      if @new_room.save
        format.html {redirect_to("/party/#{@new_room.id}") }
      else
        format.html { redirect_to rooms_path , flash: {error: "Cannot create a room"}}
      end
    end
  end

  def party
    @skip_footer = true
    @apiKey = Rails.application.secrets.open_tok_API_key
    if current_user.present?
      @user_name = current_user.email
    end

    @tok_token = opentok_token = OpenTokService.new(@room).generate_token
  end

  private
    def current_room
      @room = Room.find(params[:id])
    end


end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/rooms/create.html.haml
%h1 Room#create
%p Find me in app/views/room/create.html.haml

app/views/rooms/edit.html.haml
= bootstrap_form_for(@room) do |f|
  = f.text_area :user_id
  = f.submit "Send"

app/views/rooms/index.html.haml
.row
  .col-md-8
    .well
      %h1 Lista publicznych pokoi
      -if @rooms.any?
        %table{:class => "table table-hover"}
          %tr
            %th Name
            %th Description
            %th Link
          - @rooms.all.each do |room|
            %tr
              %td= room.name
              %td= room.description
              %td= link_to("click",party_path(room.id))
      -else
        %strong Brak dostępnych pokoi
  .col-md-4
    .well
      -if current_user && current_user.admin?
        #newRoom
          %fieldset
            %legend Stwórz nowy pokój
            = bootstrap_form_for(@new_room) do |f|
              = f.text_field :name , label: "Nazwa pokoju"
              = f.text_area :description , label: "Opis pokoju"
              = f.check_box :public, label: "Pokój publiczny"
              = f.submit

app/views/rooms/party.html.erb
<!-- <div id="invitation">Witaj w kanale  <%=@room_name%> Zaproś znajomych do konferencji dzięląć się tym liniem http://localhost:3000/party/<%= @room.id %></div> -->
<!-- <p><%=@room_name%></p> -->
 <div id="layoutContainer">
        <div id="publisherContainer"></div>
</div>


 <script src="https://swww.tokbox.com/webrtc/v2.2/js/TB.min.js" type="text/javascript" charset="utf-8"></script>
  <script src="https://code.jquery.com/jquery-1.6.2.min.js" type="text/javascript" charset="utf-8"></script>
  <script src="https://rawgit.com/aullman/opentok-layout-js/master/opentok-layout.js" type="text/javascript" charset="utf-8"></script>
      <style type="text/css" media="screen">

         #layoutContainer {
                position: absolute;
                top: 50px;
                left: 0;
                right: 0;
                bottom: 0;

            }

            #layoutContainer > div {
                display: inline-block;
                border: 1px solid #fff;
            }
    </style>
<script type="text/javascript">


//////////////////////////////////////////////////

  var apiKey =  "<%= @apiKey %>";
  var sessionId = "<%= @room.sessionId %>";
  var token = "<%= @tok_token %>";
  var name = "<%= @user_name %>";
  var session;
   var layoutContainer = document.getElementById("layoutContainer");

    var layout = TB.initLayoutContainer(layoutContainer).layout;

 var session = TB.initSession(sessionId);
    session.on("streamCreated", function(event){
        session.subscribe(event.stream, "layoutContainer", {
            insertMode: "append"
        });
        layout();
    }).connect(apiKey, token, function (err) {
        if (!err) {
            var publisher = OT.initPublisher("publisherContainer",{name: "<%= @user_name %>" });
            session.publish(publisher);
            layout();
        }
    });
var resizeTimeout;
        window.onresize = function() {
          clearTimeout(resizeTimeout);
          resizeTimeout = setTimeout(function () {
            layout();
          }, 20);
        };

        $("#layoutContainer>*").live("dblclick", function () {
            if ($(this).hasClass("OT_big")) {
                $(this).removeClass("OT_big");
            } else {
                $(this).addClass("OT_big");
            }
            layout();
        });





</script>
<!--   <input type="button" value="Connect" id ="connectLink" onClick="javascript:signal()" />
 -->